"""Deterministic markdown rendering for the weekly report. All facts and figures come
straight from computed state (task snapshot, risk scores, SQLite trend diffs) — nothing
here is generated by an LLM unless `narrative=True`, which adds one optional summary
paragraph on top of the deterministic body."""

from collections import Counter
from datetime import date
from typing import List, Optional

from .models import TaskRisk

STATUS_LABELS = {
    "todo": "To Do", "in_progress": "In Progress", "in_review": "In Review",
    "blocked": "Blocked", "done": "Done",
}
RISK_EMOJI = {"high": "🔴", "medium": "🟡", "low": "🟢"}


def render_report(
    scored: List[TaskRisk],
    trends: Optional[dict],
    stuck: list,
    run_id: int,
    sprint_name: Optional[str],
    narrative: bool = False,
) -> str:
    total = len(scored)
    by_status = Counter(tr.task.status for tr in scored)
    by_risk = Counter(tr.risk_level for tr in scored)
    by_source = Counter(tr.task.source for tr in scored)

    lines = [
        f"# Weekly Status Report — {sprint_name or 'Current Sprint'}",
        f"_Generated {date.today().isoformat()} · run #{run_id}_\n",
        "## Summary",
        f"- **{total} tasks** tracked across Jira ({by_source.get('jira', 0)}), "
        f"Asana ({by_source.get('asana', 0)}), Notion ({by_source.get('notion', 0)})",
        "- Status: " + ", ".join(f"{STATUS_LABELS[s]} {c}" for s, c in by_status.most_common()),
        f"- Risk: 🔴 High {by_risk.get('high', 0)} · 🟡 Medium {by_risk.get('medium', 0)} · "
        f"🟢 Low {by_risk.get('low', 0)}",
    ]
    if stuck:
        lines.append(f"- ⚠️ **{len(stuck)} task(s) stuck for 2+ consecutive reports** — see below")
    lines.append("")

    if narrative:
        lines.append("## Executive Summary")
        lines.append(_llm_narrative(scored, trends, stuck, sprint_name))
        lines.append("")

    lines.append("## Risk Flags")
    high = [tr for tr in scored if tr.risk_level == "high"]
    if not high:
        lines.append("_No high-risk items this week._")
    else:
        for tr in sorted(high, key=lambda x: x.task.source):
            t = tr.task
            lines.append(f"- 🔴 **[{t.source.upper()}] {t.title}** ({t.id}) — {t.assignee or 'Unassigned'}")
            for reason in tr.reasons:
                lines.append(f"  - {reason}")
    lines.append("")

    if stuck:
        lines.append("## Stuck for 2+ Sprints")
        for row in stuck:
            lines.append(
                f"- **[{row['source'].upper()}] {row['title']}** ({row['task_id']}) — "
                f"{STATUS_LABELS.get(row['status'], row['status'])}, {row['assignee'] or 'Unassigned'}"
            )
        lines.append("")

    if trends:
        lines.append("## Week-over-Week Changes")
        sections = [
            ("completed", "✅ Completed"),
            ("newly_blocked", "🆕🔴 Newly Blocked"),
            ("unblocked", "🟢 Unblocked"),
            ("new_tasks", "➕ New"),
        ]
        any_change = False
        for key, label in sections:
            items = trends.get(key) or []
            if not items:
                continue
            any_change = True
            lines.append(f"**{label} ({len(items)})**")
            for r in items:
                extra = f" — {r['blocked_reason']}" if key == "newly_blocked" and r["blocked_reason"] else ""
                lines.append(f"- [{r['source'].upper()}] {r['title']} ({r['task_id']}){extra}")
        if not any_change:
            lines.append("_No material changes since last week._")
        lines.append("")

    lines.append("## Full Task List")
    lines.append("| Source | Task | Status | Assignee | Risk |")
    lines.append("|---|---|---|---|---|")
    for tr in sorted(scored, key=lambda x: (x.task.source, x.task.status)):
        t = tr.task
        lines.append(
            f"| {t.source} | [{t.title}]({t.url or '#'}) ({t.id}) | "
            f"{STATUS_LABELS.get(t.status, t.status)} | {t.assignee or '—'} | {RISK_EMOJI[tr.risk_level]} |"
        )

    return "\n".join(lines)


def generate_narrative(stats: dict, sprint_name: Optional[str]) -> str:
    """Turn a small dict of pre-computed stats into one executive-summary paragraph. The
    LLM only ever phrases numbers that code already computed — it never counts anything
    itself. Shared by the deterministic report's `--narrative` flag and the chat tool
    `get_executive_summary`, so both paths use the exact same prompt."""
    from .config import get_llm
    llm = get_llm()
    prompt = (
        "Write a 3-4 sentence executive summary for a program manager, based on these "
        f"sprint stats for {sprint_name or 'the current sprint'}: {stats}. "
        "Be direct and specific about risk. No preamble, no headers."
    )
    return llm.invoke(prompt).content


def stats_from_scored(scored: List[TaskRisk], trends: Optional[dict], stuck: list) -> dict:
    return {
        "total_tasks": len(scored),
        "high_risk": sum(1 for t in scored if t.risk_level == "high"),
        "stuck_2plus_sprints": len(stuck),
        "completed_this_week": len(trends["completed"]) if trends else 0,
        "newly_blocked_this_week": len(trends["newly_blocked"]) if trends else 0,
    }


def _llm_narrative(scored, trends, stuck, sprint_name) -> str:
    try:
        stats = stats_from_scored(scored, trends, stuck)
        return generate_narrative(stats, sprint_name)
    except Exception as e:
        return f"_(narrative summary unavailable: {e})_"
